#!/usr/bin/env python


import sys
import os

from src.cbopensource.connectors.lastline.bridge import LastlineConnector

version = "2.0.0"

if __name__ == "__main__":
    name = "lastline"

    # set the path to the CA certificate PEM file to our local cache
    cacert_pem_path = "/usr/share/cb/integrations/lastline/cacert.pem"
    if os.path.isfile(cacert_pem_path):
        os.environ["REQUESTS_CA_BUNDLE"] = cacert_pem_path

    daemon = LastlineConnector(name,
                                      configfile="/etc/cb/integrations/lastline/connector.conf",
                                      work_directory="/usr/share/cb/integrations/lastline/db")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print("%s - version %s" % (name, version))
        else:
            print("Unknown command: %s" % sys.argv[1])
            sys.exit(2)

    else:
        print("Usage: %s start|stop|restart|version" % sys.argv[0])
        sys.exit(2)

    sys.exit(0)